lookup_table = {
    "LATIN": {
        "CAPITAL LETTER": {
            "A": "A",
            "AE": "Æ",
            "B": "B",
            "C": "C",
            "D": "D",
            # "DZ": "Ǳ",
            "EZH": "Ʒ",
            "E": "E",
            "F": "F",
            "G": "G",
            "H": "H",
            "I": "I",
            "J": "J",
            "K": "K",
            "L": "L",
            "N": "N",
            "O": "O",
            "P": "P",
            "R": "R",
            "S": "S",
            # "SCHWA": "Ə",
            "T": "T",
            "U": "U",
            "V": "V",
            "W": "W",
            "Y": "Y",
            "Z": "Z",
        },
        "SMALL LETTER": {
            "A": "a",
            "AE": "æ",
            "B": "b",
            "C": "c",
            "D": "d",
            # "DZ": "ǳ",
            "E": "e",
            "EZH": "ʒ",
            "F": "f",
            "G": "g",
            "H": "h",
            "I": "i",
            "J": "j",
            "K": "k",
            "L": "l", 
            # "LAMBDA": "λ",
            "M": "m",
            "N": "n",
            "O": "o",
            "P": "p",
            "Q": "q",
            "R": "r",
            "S": "s",
            # "SCHWA": "ə",
            "T": "t",
            "U": "u",
            "V": "v",
            "W": "w",
            "Y": "y",
            "Z": "z",
        },
    },        
}




